# Generated by Django 5.2.17 on 2026-08-30 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_original_price_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone / WhatsApp Number')),
                ('address', models.TextField(verbose_name='Complete Shipping Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Grand total including shipping', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending (Unconfirmed)'), ('Confirmed', 'Confirmed / Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of item at the time of purchase', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
        ),
    ]
