# Generated by Django 5.2.17 on 2026-09-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was cryptographically verified', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracker_token',
            field=models.CharField(blank=True, help_text='Official Safepay Order Tracker Token (track_...)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Order Reference'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Gateway Transaction Reference / Receipt ID', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment (Safepay: Cards / JazzCash / Easypaisa)')], default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid / Awaiting Payment'), ('PROCESSING', 'Processing with Payment Gateway'), ('PAID', 'Paid & Verified'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Payment Cancelled by Customer'), ('REFUNDED', 'Refunded')], db_index=True, default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending (Awaiting Payment / Processing)'), ('Confirmed', 'Confirmed / Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price at checkout time', max_digits=10),
        ),
    ]
