# Generated by Django 5.2.17 on 2026-08-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g. Sindhi Topi)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated or manual)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description of this collection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Product title (e.g. Sindhi Ajrak Mirror Work Topi)', max_length=200)),
                ('slug', models.SlugField(help_text='URL identifier for product details page', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed description of fabric, design, and style')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Pakistani Rupees (PKR)', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Original photograph of the topi', null=True, upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available inventory units')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this topi belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
